### ISSUE TITLE
无法注册牛子

### ISSUE THREAD

**Issue by decatri** [tkgs0/nonebot-plugin-dicky-pk#2]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-dicky-pk/issues) 中没有相同或相似的问题。

### dicky-pk

v0.1.3

### go-cqhttp

v1.0.0-rc4

### nonebot

2.0.0rc3

### Python

3.10

### 操作系统

Windows 10 专业版22H2 19045.2486 

### 问题描述

之前看那个issue在env内加上了还是没能解决，貌似是转码出现了什么问题，还请作者看看是不是，谢谢。

### 复现步骤

/注册牛子
或者
//注册牛子

### 期望行为

成功执行

### 实际行为

失败，且你还没有牛子！

### 日志信息

02-07 15:02:31 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_dicky_pk) failed.
Traceback (most recent call last):
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot_plugin_dicky_pk\__init__.py", line 130, in _
    dicky_run(KEYWORDS['sign_up'][0], bot, matcher, event)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot_plugin_dicky_pk\__init__.py", line 54, in dicky_run
    chinchin(bot, matcher, msg, uid, gid, at_id, nickname, fuzzy_match)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot_plugin_dicky_pk\src\main.py", line 65, in message_processor
    return Chinchin_me.sign_up(bot, matcher, qq, group)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot_plugin_dicky_pk\src\main.py", line 343, in sign_up
    new_length = Config.new_chinchin_length()
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot_plugin_dicky_pk\src\config.py", line 42, in new_chinchin_length
    min = cls.get_config('new_chinchin_length_random_min')
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot_plugin_dicky_pk\src\config.py", line 37, in get_config
    config = cls.read_config()
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot_plugin_dicky_pk\src\config.py", line 32, in read_config
    cache = json.load(f)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 188: illegal multibyte sequence

**Comment by tkgs0** [comment]
确实是配置文件的编码问题, 已合并来自 [mobyw](https://github.com/mobyw) 的提交修复 (#3) 并发布新版本 `0.1.4`

**Comment by decatri** [comment]
好的，可以正常注册了，谢谢
